### ISSUE TITLE
Removing Viewpager External Dependency     

### ISSUE THREAD

**Issue by HimanshuS01** [systers/malaria-app-android#140]
Currently app is using the following library for Viewpager indicator. 
`compile 'com.viewpagerindicator:library:2.4.1@aar'`

We can replace it by custom made Viewpager (along with dot indicators) and UI will remain *exactly* the same. Also the dots color being currently used is not in contrast and less visible which should be changed.
I will like to work on these if its intended enhancement.  
@chhavip @MeepyMay @yatna

**Comment by chhavip** [comment]
For now this is not needed as we are not facing any grave issues with the external library.

**Comment by HimanshuS01** [comment]
Hey @chhavip ,this issue will reduce the apk size and also reduce external dependencies from app ,thereby enhancing the app performance.

**Comment by yatna** [comment]
@HimanshuS01 As told by @chhavip we are not facing any issues with the viewpagerindicator  library. Using a custom made viewpager will increase our codebase with no evident changes in the app. Also, since the number of swipes made while using the app are small, I don't think optimizing it will make any evident change to the user. As far as the apk size is considered , if you can reduce the size with a good margin, only then we can look forward into the issue.
If you really want to work on this, you can send us a PR, but again I cannot guarantee if we can merge it, even if it has the exact same UI and works perfectly.

**Comment by anubhakushwaha** [comment]
@HimanshuS01 Working on this?

**Comment by HimanshuS01** [comment]
@anubhakushwaha yes.  I am on it.

**Comment by geekanamika** [comment]
Viewpager is removed from application & analysis screens are now shift to profile item in bottom navigation. Closing this issue.
