### ISSUE TITLE
disable Toast message "Error retrieving data! Loading data from cache" when data present in cache

### ISSUE THREAD

**Issue by shreyans29** [systers/malaria-app-android#244]
There is no point in showing the error when data is available in cache.  When Data is not available we could use a simpler toast message like "Internet Disable" or something similar which could make sense to a layman.  Can I submit a PR for this @chhavip  @yatna @anubhakushwaha ? 
![screenshot_2017-03-10-20-43-10-312_com peacecorps malaria](https://cloud.githubusercontent.com/assets/8592568/23800498/a0d4286a-05d2-11e7-80f1-fb4d05bd8ec2.png)

**Comment by geekanamika** [comment]
Adding to it , If data is not available in cache , it'll keep showing fetching.
Expected behaviour:
* speaker button should be disabled if data is not available through internet/cache
* Toast should be replaced with snackbar probably in case no data

![loading data from cache](https://user-images.githubusercontent.com/16922933/37398710-5da34bd4-27a5-11e8-84b8-9bebb88ba6d4.gif)

**Comment by geekanamika** [comment]
Infohub is not receiving any data from network, we can open this issue later.
