### ISSUE TITLE
Better code packaging

### ISSUE THREAD

**Issue by yogeshbalan** [systers/malaria-app-android#60]
For better understanding of code, it is always advisable to package classes, receivers, services, ui-widgets, fragments, activities etc separately.  
According to current set of classes, the code can be divided into following packages
- Receiver
- utils
- data
- fragments
- activities
- ui
- model
- volley
- service

This will ensure new developers to understand and debug code easily

**Comment by yatna** [comment]
Another hierarchy can be dividing the classes into packages based on different app sections such as Info Hub, Trip Planner, Home etc.

**Comment by yogeshbalan** [comment]
If we have any service or fragment that is used in two or more places, then above method wouldn't fit. @yatna , What do you say?

**Comment by yatna** [comment]
@yogeshbalan Currently, I do not think ,there is any fragment which has been used in two sections of the app. Also the service class for both Trip Reminder Alarm and Medication Alarm is different.

**Comment by yogeshbalan** [comment]
@yatna ,  Not now, but in future course, this situation may occur where same piece of code is used in more than two different places. I agree with the fact that dividing code package into app section is more readable and straight but not modular.

**Comment by yatna** [comment]
@yogeshbalan Well there are pros and cons to both the approaches. However, as far as any common class is considered in future, it can be placed outside both the packages or in a separate package depending on it's feature, if it occurs in two section or more. 
My primary concern with the first approach is the overcrowding in some packages, since most of the classes will belong to fragment and activity package and hence would not serve the very purpose of code division. The first approach is clearly  a better approach for apps having lots of diverse components such recievers,services, utils and database classes, but for a app containing mostly UI components, I feel dividing on the basis of features can be  better. Lets see what @ankita-kalra has to say on this :-)

**Comment by yogeshbalan** [comment]
@ankita-kalra , can you please take a look at this. Thanks

**Comment by yatna** [comment]
Fixed in GSoC16. @chhavip Please close this issue too.
